name: Conventional Commits Check
on:
  pull_request:
    branches: [main]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: webiny/action-conventional-commits@7f91b1595ca1951cdb671ddc9f07a49081ec5b69 # v1.4.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optionally, restrict allowed types:
          # allowed-commit-types: "feat,fix,docs,style,refactor,test,chore,ci"
